### ISSUE TITLE
[3Di]: simplify method to delete pre-klondike models

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#31]
### Contact Details

Florian/Lisanne

### Incident Type

Wish

### 3Di component

API - v3 (Default)

### What happened?

Currently, the workflow to delete pre-klondike models is very cumbersome: any related schematisations and revisions need to be manually deleted, prior to deleting the models themselves. 

Potential solutions:
-enable clients to delete models in the management windows :pray:
-make a script
-add a cascade on_delete?

**Comment by Patrick-Nijman** [comment]
@JJFlorian I have discussed with Casper and he states it's possible to delete Pre-Klondike models. They don't have schematisations but revisions. Models should be deletable. Maybe you mean Post-Klondike? Also for further investigation it would really be helpfull to have a link to a model (url or id+type) or some information which shows clearly why this is a problem. It now takes too much time to find out what the problem is and how we would be able to solve it.

Thanks!

Patrick
