### ISSUE TITLE
[Lizard]: show time series name in drop down menu iso location name+parameter

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#33]
### Contact Details

Florian/Emile(& Ivar)

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=e0d8946f-ae98-45a9-9e20-cf302b420de1

### Incident Type

Wish

### 3Di component

Viewer

### What happened?

The drop down menu of multiple time series related to one location show the location name + parameter. Often, this results in identical names, which makes it difficult to distinguish the time series. Currently, a workaround is to create a unique parameter for each time series, which is quite cumbersome. 

A nice fix would be to replace the location name by the time series name. The location name is irrelevant anyways, as it is shown just above the drop down menu.

An example with varying parameter names:
![image](https://user-images.githubusercontent.com/73856313/157848152-35dc6448-b65a-4f18-aea9-7a3f2f22a66c.png)

### How to Reproduce?

Open calculater.
Press 1,
Press +,
Press 1,
Press =

### What did you expect and what was the actual result?

I expected 2 but the calculator returned 3

### Add screenshots, video's etc

The maximum size for files is 25MB and the maximum size for images is 10MB.

### Additional info

Anything else you would like to share?

**Comment by lexvand** [comment]
We have chosen specifically for the combination of location__name/observation_type__parameter as it suits most operational data flows, e.g. from FEWS systems. We know in some cases it provides duplicate information in relation to the related asset or it is a challenge to configure it in a way that all members are unique. Making changes in the current setup would break a lot of existing use cases.

My suggestion in this case would be to create multiple locations instead of multiple observation types and distribute the timeseries that way. It makes more sense to treat different wells as different locations related to this asset. In that case you can indicate the well in the location name and keep that as short as possible by leaving out the asset name.
