### ISSUE TITLE
[3Di]: Schematisation gets generated to threedimodel, even with multiple errors in checker 

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#70]
### Contact Details

Stijn O

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=ca138d68-21d3-4400-8698-a93aeb80344e

### Incident Type

Error

### What priority should we assign to this submission?

Prio3 Not urgent

### 3Di component

API - v3 (Default)

### What happened?

Stijn created a model which resulted in NaN values as output after forcing the model with rain. A  dry simulation resulted in no errors.

The problem according to Jonas is that the model should never have been able to be generated, since the schem checker fired multiple warnings. See screenshot.

### How to Reproduce?

 The revision can be found at https://management.3di.live/schematisations/5540/40908.

### What did you expect and what was the actual result?

The model should not be generated

### Add screenshots, video's etc

![image](https://user-images.githubusercontent.com/73856313/178443696-c4831316-2283-4cc8-a1ad-0045875ff226.png)

### Additional info

Anything else you would like to share?

**Comment by Patrick-Nijman** [comment]
@JJFlorian 

When we create a 3Di Model we will check the sqlite on errors and display them. We don't run the raster checker because it basically needs to be rewritten. This is on the roadmap. But we won't change this soon.

For now it's best to run the raster checker seperately before creating a model or try to do this if results are not what you expected.
